on:
  push:
    branches:
      - main

jobs:
  explore-env:
    runs-on: ubuntu-latest
    name: Exploring intenal environment of a runner - host
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: two
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Exploring intenal environment of a runner - host
        run: |
          echo "current directory: `pwd`"
          echo "current user: `whoami`"
          echo "current user permissions: `sudo -l`"
          echo "------------------running svc------------------"
          ps aux
          echo "------------------docker ps------------------"
          docker ps
          
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host localhost --port 3306 -uroot -ppassword -e "SHOW DATABASES"
          
          
