on:
  push:
    branches:
      - main

jobs:
  explore-env:
    runs-on: ubuntu-latest
    name: Exploring intenal environment of a runner
    steps:

      - name: Exploring intenal environment of a runner
        run: |
          echo "current directory: `pwd`"
          echo "current user: `whoami`"
          echo "current user permissions: `sudo -l`"
          echo "------------------running svc------------------"
          ps aux
          echo "------------------------------------"
          echo "------------------docker images------------------"
          docker images
          echo "------------------------------------"
          echo "------------------docker ps------------------"
          docker ps
          echo "------------------------------------"
          
